name: Bug-Report
description: Melden Sie einen Fehler auf StreamProtect!
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibe dein Problem!
      description: Beschreibe dein Problem Genau!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduktionsschritte
      description: Beschreibe wie man den Fehler reproduziert.
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Schreibe was normalerweise passieren sollte!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Zusatz
      description: Screenshots, Videos etc.
  - type: input
    id: discord
    attributes:
      label: Discord Name
      description: Wie lautet dein Discord Name
      placeholder: e.g. ğ–ğ–ƒğ•­ğ–‘ğ–†ğ–ˆğ–_ğ•¿ğ–Šğ–—ğ–—ğ–”ğ–—ğ–ƒğ–#0187
    validations:
      required: true
