name: Bug-Report
description: Report a bug on StreamProtect!
labels: ['bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Describe your problem!
      description: Describe your problem exactly!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproductive steps
      description: Describe how to reproduce the bug.
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Write what should normally happen!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additive
      description: screenshots, videos, etc.
  - type: input
    id: discord
    attributes:
      label: Discord-Name
      description: What is your discord name
      placeholder: e.g. ğ–ğ–ƒğ•­ğ–‘ğ–†ğ–ˆğ–_ğ•¿ğ–Šğ–—ğ–—ğ–”ğ–—ğ–ƒğ–#0187
    validations:
      required: true
